Adding collector inside of .yml workflows so i don't have to specify every single build names for branch protection rules

diff --git a/.github/workflows/linux_build.yml b/.github/workflows/linux_build.yml
--- a/.github/workflows/linux_build.yml
+++ b/.github/workflows/linux_build.yml
@@ -58,3 +58,18 @@ jobs:
 
     - name: Build
       run: cmake --build build
+
+  # Collector
+  ci-success:
+    name: WFX Linux Build Success
+    runs-on: ubuntu-latest
+    if: always()
+    needs: [build] # Wait for the 'build' matrix to finish
+    steps:
+      - name: Check Status
+        run: |
+          if [[ "${{ contains(needs.*.result, 'failure') }}" == "true" || "${{ contains(needs.*.result, 'cancelled') }}" == "true" ]]; then
+            echo "Build matrix failed."
+            exit 1
+          fi
+          echo "All builds passed!"
